# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bb2804aa1ef6eded2d7915b3b3b3a6ff23f773233dad3d7bbe273a4434c0646ba6b0298a5fa34942eedc6e9c55044f117e1ca24986534e3ac1b77254aceba126

test:
  secret_key_base: d592fecf753076b537f4a72ab035c4803a92209ef5e1cb76d03cd1f4030db16d079626ce608e3db7779707ef7f5ab5ea2a2c213488a4d9c2f2e3dc8e41ecbfcf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
